// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_app/test/data/surf_record_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_app/data/database_helper.dart' as _i3;
import 'package:flutter_app/models/surf_record.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i3.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i4.Future<_i2.Database>);

  @override
  _i4.Future<int> insertSurfRecord(_i5.SurfRecord? record) =>
      (super.noSuchMethod(
            Invocation.method(#insertSurfRecord, [record]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.SurfRecord>> getSurfRecords() =>
      (super.noSuchMethod(
            Invocation.method(#getSurfRecords, []),
            returnValue: _i4.Future<List<_i5.SurfRecord>>.value(
              <_i5.SurfRecord>[],
            ),
          )
          as _i4.Future<List<_i5.SurfRecord>>);

  @override
  _i4.Future<_i5.SurfRecord?> getSurfRecordByDate(String? date) =>
      (super.noSuchMethod(
            Invocation.method(#getSurfRecordByDate, [date]),
            returnValue: _i4.Future<_i5.SurfRecord?>.value(),
          )
          as _i4.Future<_i5.SurfRecord?>);

  @override
  _i4.Future<int> updateSurfRecord(_i5.SurfRecord? record) =>
      (super.noSuchMethod(
            Invocation.method(#updateSurfRecord, [record]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteSurfRecord(String? date) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSurfRecord, [date]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteAllSurfRecords() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllSurfRecords, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}
