// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_app/test/viewmodels/surf_record_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_app/data/surf_record_repository.dart' as _i2;
import 'package:flutter_app/models/surf_record.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SurfRecordRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSurfRecordRepository extends _i1.Mock
    implements _i2.SurfRecordRepository {
  MockSurfRecordRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> insert(_i4.SurfRecord? record) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [record]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.SurfRecord>> getAllRecords() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRecords, []),
            returnValue: _i3.Future<List<_i4.SurfRecord>>.value(
              <_i4.SurfRecord>[],
            ),
          )
          as _i3.Future<List<_i4.SurfRecord>>);

  @override
  _i3.Future<_i4.SurfRecord?> getRecordByDate(String? date) =>
      (super.noSuchMethod(
            Invocation.method(#getRecordByDate, [date]),
            returnValue: _i3.Future<_i4.SurfRecord?>.value(),
          )
          as _i3.Future<_i4.SurfRecord?>);

  @override
  _i3.Future<int> update(_i4.SurfRecord? record) =>
      (super.noSuchMethod(
            Invocation.method(#update, [record]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> delete(String? date) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [date]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}
